### ISSUE TITLE
Media Library's style has been messed

### ISSUE THREAD

**Issue by wonderbeyond** [petedermott/mezzanine#5]
**By these code:**
https://github.com/fermorltd/mezzanine/blob/6aeab46c701743e76d06d2e87cce1764f7423c01/mezzanine/core/templates/admin/base_site.html#L61-L77

**Affected page:**
![image](https://user-images.githubusercontent.com/228361/75510008-70710900-5a24-11ea-8ade-a2640f7a290a.png)

**Comment by wonderbeyond** [comment]
**Also affected:**

![image](https://user-images.githubusercontent.com/228361/75510311-803d1d00-5a25-11ea-8222-13312605b2f2.png)

**Comment by petedermott** [comment]
Thanks, this should be fixed by [this commit](https://github.com/fermorltd/mezzanine/commit/15045c1d2f62ffce68af8e7e47aff0394068c5a6)

Just FYI, please make sure you are also using the 2.2-compat branch of [filebrowser_safe](https://github.com/fermorltd/filebrowser-safe/tree/2.2-compat)

Let me know if its still an issue

**Comment by wonderbeyond** [comment]
I'm sorry I am still experiencing the same issue:

![image](https://user-images.githubusercontent.com/228361/75554378-2e23e800-5a75-11ea-8142-d42ddc500435.png)


It seems that these two lines are making the trouble:

https://github.com/fermorltd/mezzanine/blob/15045c1d2f62ffce68af8e7e47aff0394068c5a6/mezzanine/core/templates/admin/base_site.html#L69
https://github.com/fermorltd/mezzanine/blob/15045c1d2f62ffce68af8e7e47aff0394068c5a6/mezzanine/core/templates/admin/base_site.html#L76

**Comment by petedermott** [comment]
OK, it looks like all the overrides that were in there were specific "hacks" for Fermor projects, I've removed them in [this commit](https://github.com/fermorltd/mezzanine/commit/746c0fb73654225d56796dab322758a293fa15b9).

Let me know if its still an issue!

**Comment by wonderbeyond** [comment]
Thanks, no problem now.
